# Generated by Django 4.2.5 on 2023-10-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_admin_geocache_find_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='radius',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
    ]
