# Generated by Django 4.2.5 on 2023-10-13 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_geocache_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='geocache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.geocache'),
        ),
        migrations.AlterField(
            model_name='geocache',
            name='radius',
            field=models.IntegerField(null=True),
        ),
    ]
