# Generated by Django 4.2.5 on 2023-11-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
