# Generated by Django 4.2.5 on 2023-11-10 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_geocache_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_geocaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
