# Generated by Django 4.2.5 on 2023-11-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_geocache_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='admin_date',
            field=models.DateTimeField(null=True),
        ),
    ]
