# Generated by Django 4.2.5 on 2023-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_geocache_admin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
