# Generated by Django 4.2.5 on 2023-11-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_geocache_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='find_count',
            field=models.IntegerField(default=0),
        ),
    ]
