# Generated by Django 4.2.4 on 2023-11-15 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_find_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocache',
            name='hint',
        ),
        migrations.AddField(
            model_name='geocache',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('geocache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='users.geocache')),
            ],
        ),
    ]
