# Generated by Django 4.2.5 on 2023-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_find_hint_count_alter_geocache_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hint',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
